### PR TITLE
Remove saving/closing the session. Fixes #12

### LINKED ISSUE #12: Symphony 2.6: Cookie handling is broken
Using Symphony 2.6, there are issues with the field's cookie handling:

1. The user is logged out after having seen a page with an HTML Panel.
2. The Cookie does not allow using "admin" type pages for an HTML panel. So probably the cookie is incorrect.

### PR DESCRIPTION
**Pull request by michael-e**
It is unclear why it has been implemented like this, but it doesn't work properly with Symphony 2.6. Since we are not sure how the fix will behave with Symphony pre 2.6, we release a new version compatible with Symphony 2.6.x.

### CODE REVIEW

**Comment by nitriques** [comment]
Thanks Micheal,

1.5.0 has never been release, so I do not see the point of creating 1.5.1.

And could you also add max="2.6.x" to the release please? Thanks!

**Comment by nitriques** [comment]
> 1.5.0 has never been release,

But the tag exisits, oh boy...

**Comment by michael-e** [comment]
Sorry for pushing the tag to this repo by accident. But if you merge the PR, you will see that the tag exists for the first commit. Afterwards I decided to clean up, so I tagged 1.5.1.

Sorry for the confusion.

**Comment by nitriques** [comment]
Ok now worries.

> And could you also add max="2.6.x" to the release please? Thanks!

:)

**Comment by michael-e** [comment]
> And could you also add max="2.6.x" to the release please? Thanks!

Wouldn't I have to release 1.5.2 then? (Otherwise this info would only be in the master branch, but not in the latest release.)

**Comment by nitriques** [comment]
> Wouldn't I have to release 1.5.2 then? 

I do not think so...

> Otherwise this info would only be in the master branch, but not in the latest release.

I do not understand... We do not even have an integration branch so for now, that's ok ;)

**Comment by michael-e** [comment]
I mean: If people download the latest pre-compiled ZIP file here from Github (1.5.1), they will have no max compatibility info. So I think that we should release 1.5.2 (so ZIP-downloaders will download that one) if we change max compatibility.

**Comment by nitriques** [comment]
> if we change max compatibility.

Well we do not change it, we just set it ;) And 2.6.x is our latest so the information does not actually change. But I do not mind if you want to create 1.5.2 ;)

**Comment by michael-e** [comment]
Done. Please pull.

**Comment by nitriques** [comment]
Thanks!

**Comment by nitriques** [comment]
I've created a integration branch for future work :) Did you creates the tag ? If not, I'll gladly do it.

**Comment by michael-e** [comment]
I pushed the tags now (they have not been merged).

**Comment by michael-e** [comment]
Thanks a lot. I will try and make it better next time. (Seems I am bit rusted concerning Git.)

**Comment by nitriques** [comment]
:P

**Pull request merged**
